using System;
using System.Collections.Generic;
using System.Linq;

namespace Problems {
  public class P2FibonaccirSequence: ISolution {
    public string Description {
      get {
        return "Each new term in the Fibonacci sequence is generated by adding the previous two terms."
               + " By starting with 1 and 2, the first 10 terms will be"
               + ":1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..."
               + "By considering the terms in the Fibonacci sequence whose values do not "
               + "exceed four million, find the sum of the even-valued terms.";
      }
    }

    public void Solve() {
      const int Maximum = 4000000;
      var multiples = new List<double>();
      multiples.AddRange( new double[] { 1, 2 } );
      Console.WriteLine( Description ); 
      
      for ( var x = 1; multiples[x] + multiples[x - 1] < Maximum; x++ ) {
        multiples.Add( multiples[x] + multiples[x-1] );
      }

      Console.WriteLine( "Result is {0} ", multiples.Where( number => number % 2 == 0 ).Sum() );
    }
  }
}